CREATE TABLE Team(name TEXT PRIMARY KEY, full_name TEXT UNIQUE, SKILL INTEGER);
CREATE TABLE Competition(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, country TEXT);
CREATE TABLE Tournament(id INTEGER PRIMARY KEY AUTOINCREMENT, competition_id INTEGER FOREIGN KEY REFERENCES Competition, year INTEGER);